# Generated by Django 3.2.6 on 2021-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qualifications', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=50)),
                ('image1', models.ImageField(default='', upload_to='images')),
                ('image2', models.ImageField(default='', upload_to='images')),
                ('image3', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
